# Generated by Django 2.1.2 on 2018-10-18 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('IdCiudad', models.IntegerField(primary_key=True, serialize=False, verbose_name='ciudad')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut')),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('FechaNaci', models.DateField()),
                ('Telefono', models.IntegerField()),
                ('Correo', models.TextField()),
                ('IdCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('usuario', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='login')),
                ('contraseña', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('IdRegion', models.IntegerField(primary_key=True, serialize=False, verbose_name='region')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoVivienda',
            fields=[
                ('IdTipoViv', models.IntegerField(primary_key=True, serialize=False, verbose_name='tipoviv')),
                ('Descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='IdRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='IdTipoViv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TipoVivienda'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='IdRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Region'),
        ),
    ]
